const data = {
    "Pain":[
        {
            "name":"Pain",
            "image":require("./asset/Kebab.png"),
            "prix":2
        },
        {
            "name":"Galette",
            "image":require("./asset/Galette.png"),
            "prix":2
        }
    ],
    "Viande":[
        {
            "name":"Viande",
            "image":require("./asset/Viande.png"),
            "prix":2
        },
        {
            "name":"Tofu",
            "image":require("./asset/Tofu.png"),
            "prix":2
        }
    ],
    "Salade":[
        {
            "name":"Salade",
            "image":require("./asset/Salade.png"),
            "prix":2
        },
        {
            "name":"Tomates",
            "image":require("./asset/Tomate.png"),
            "prix":2
        },
        {
            "name":"Oignons",
            "image":require("./asset/Oignon.png"),
            "prix":2
        }
    ],
    "Sauces":[
        {
            "name":"Blanche",
            "image":require("./asset/Sauce-blanche.png"),
            "prix":2
        },
        {
            "name":"Harissa",
            "image":require("./asset/Sauce-harissa.png"),
            "prix":2
        },
        {
            "name":"Andalouse",
            "image":require("./asset/Sauce-andalouse.png"),
            "prix":2
        },
        {
            "name":"BBQ",
            "image":require("./asset/Sauce-bbq.png"),
            "prix":2
        },
        {
            "name":"Ketchup",
            "image":require("./asset/Sauce-ketchup.png"),
            "prix":2
        },
        {
            "name":"CURRY",
            "image":require("./asset/Sauce-curry.png"),
            "prix":2
        }
    ]
        
    
}
export default data